////delete when class is created outside package
//<dependency>
//<groupId>org.projectlombok</groupId>
//<artifactId>lombok</artifactId>
//<version>1.18.32</version>
//<scope>provided</scope>
//</dependency>
//<dependency>
//<groupId>org.springframework.boot</groupId>
//<artifactId>spring-boot-starter-data-mongodb</artifactId>
//<version>3.2.4</version>
//</dependency>
//<dependency>
//<groupId>org.mongodb</groupId>
//<artifactId>mongodb-driver-core</artifactId>
//<version>4.11.1</version>
//</dependency>
//<dependency>
//<groupId>org.junit.jupiter</groupId>
//<artifactId>junit-jupiter-api</artifactId>
//<version>5.10.2</version>
//<scope>test</scope>
//</dependency>
//<dependency>
//<groupId>de.flapdoodle.embed</groupId>
//<artifactId>de.flapdoodle.embed.mongo.spring30x</artifactId>
//<version>4.6.2</version>
//<scope>test</scope>
//<optional>true</optional>
//</dependency>
//<dependency>
//<groupId>org.springframework.boot</groupId>
//<artifactId>spring-boot-starter-web</artifactId>
//<version>3.2.3</version>
//<scope>compile</scope>
//</dependency>
//<dependency>
//<groupId>org.springframework.boot</groupId>
//<artifactId>spring-boot-starter-test</artifactId>
//<version>3.2.4</version>
//<scope>test</scope>
//</dependency>